baseURL = 'https://qoheleth.post-self.ink'
languageCode = 'en-us'
title = 'Qoheleth'
theme = 'maddybook'
paginatePath = ''
disablePathToLower = true

[permalinks]
    post = '/:filename/'

[params]
    author = 'Madison Scott-Clary'
    home = 'https://makyo.ink'
    copyright = 2020
    customCSS = ['/css/qoheleth.css']
    subtitle = 'Post-Self book I'
    subtitleLink = 'https://post-self.ink'

[markup.goldmark.renderer]
    unsafe = true

